"""empty message

Revision ID: 11adee8005ed
Revises: c3ef080253db
Create Date: 2019-12-19 12:48:09.488672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11adee8005ed'
down_revision = 'c3ef080253db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'track', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'track', 'user', ['user_name'], ['username'])
    # ### end Alembic commands ###
