"""empty message

Revision ID: 1fe7ad2c3351
Revises: 7984dd19645c
Create Date: 2019-12-12 12:19:03.066514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fe7ad2c3351'
down_revision = '7984dd19645c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('location', sa.Column('w3w', sa.String(length=15), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('location', 'w3w')
    # ### end Alembic commands ###
