"""empty message

Revision ID: 3bbb2e1e8b34
Revises: c2bb6ef3d1d0
Create Date: 2019-12-11 10:51:03.683665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bbb2e1e8b34'
down_revision = 'c2bb6ef3d1d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Tracks', sa.Column('logtime', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_Tracks_logtime'), 'Tracks', ['logtime'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Tracks_logtime'), table_name='Tracks')
    op.drop_column('Tracks', 'logtime')
    # ### end Alembic commands ###
