"""empty message

Revision ID: 9143ffb1b6d7
Revises: 
Create Date: 2020-01-07 12:58:08.675259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9143ffb1b6d7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('track',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('alias', sa.String(length=30), nullable=True),
    sa.Column('url', sa.String(length=70), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('share_team', sa.Boolean(), nullable=True),
    sa.Column('user_name', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_track_alias'), 'track', ['alias'], unique=False)
    op.create_index(op.f('ix_track_create_time'), 'track', ['create_time'], unique=False)
    op.create_index(op.f('ix_track_name'), 'track', ['name'], unique=True)
    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(length=15), nullable=True),
    sa.Column('logtime', sa.DateTime(), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('positionAccuracy', sa.Float(), nullable=True),
    sa.Column('altitude', sa.Float(), nullable=True),
    sa.Column('altitudeAccuracy', sa.Float(), nullable=True),
    sa.Column('speed', sa.Float(), nullable=True),
    sa.Column('heading', sa.Float(), nullable=True),
    sa.Column('w3w', sa.String(length=60), nullable=True),
    sa.Column('timeStamp', sa.DateTime(), nullable=True),
    sa.Column('track_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['track_id'], ['track.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_location_logtime'), 'location', ['logtime'], unique=False)
    op.create_index(op.f('ix_location_timeStamp'), 'location', ['timeStamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_location_timeStamp'), table_name='location')
    op.drop_index(op.f('ix_location_logtime'), table_name='location')
    op.drop_table('location')
    op.drop_index(op.f('ix_track_name'), table_name='track')
    op.drop_index(op.f('ix_track_create_time'), table_name='track')
    op.drop_index(op.f('ix_track_alias'), table_name='track')
    op.drop_table('track')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
