"""empty message

Revision ID: a96b4f40c581
Revises: 6c591ae58a22
Create Date: 2019-12-17 08:55:38.861467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a96b4f40c581'
down_revision = '6c591ae58a22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('track', sa.Column('alias', sa.String(length=30), nullable=True))
    op.create_index(op.f('ix_track_alias'), 'track', ['alias'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_track_alias'), table_name='track')
    op.drop_column('track', 'alias')
    # ### end Alembic commands ###
